# REST Client - Todo routes

# @name getRoot
GET {{baseUrl}}

###

# @name getAllTodos
GET {{baseUrl}}/todos

### 

# @name createNewTodo
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "description": "Mow the lawn"
}

###

@todoId = {{createNewTodo.response.body.$.todoId}}

# @name getTodo
GET {{baseUrl}}/todos/{{todoId}}

###

# @name updateTodo
PUT {{baseUrl}}/todos/{{todoId}}
Content-Type: application/json

{
  "isDone": true
}

###

# @name deleteTodo
DELETE {{baseUrl}}/todos/{{todoId}}
